### ISSUE TITLE
Authentication Issues in Initialization Job

### ISSUE THREAD

**Issue by jacoblElementor** [databricks-industry-solutions/security-analysis-tool#125]
Hi,
I am trying to setup SAT in my AWS based account.
I've created the SAT configuration and components using TF.
I am using an account level SP, which has Account, Workspace, Metastore admins permissions for authentication.
Setup Notebooks 1-4 from the Setup folder work well. (_notebooks/Setup/1...4_)
When getting to step 5 (_notebooks/Setup/5. import_dashboard_template_), I am getting the following error: `Invalid access token, check PAT configuration value for this workspace.`

After investigating the issue, I've found that from setup notebook 5 and forward, the code uses the workspace auth token from the secret `sat-token-<workspace_id>` straight forward instead of creating and AWSOAuth Token and using that - as it is done in the previous steps. I tried changing the code to create an AWS oauth token and that solved the issues.
So, is there anything I'm missing, should the workspace token work as is, or is this a bug in the code?

**Comment by arunpamulapati** [comment]
Yes, in the current version "workspace_PAT" is required for that step.
 https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/terraform/aws/terraform.tfvars
We are working on removing that dependency in the next release. 
Can you please send me an email to arun@databricks.com so that we can connect live and discuss if you have further questions and maybe if you are interested in making a PR for this change?

**Comment by arunpamulapati** [comment]
Working as expected for the current configurations. We will be updating in the next release to remove the dependency on PAT for importing dashboards.
