### ISSUE TITLE
IA-1 - Enable single sign-on Check - Account Level VS Workspace Level

### ISSUE THREAD

**Issue by jacoblElementor** [databricks-industry-solutions/security-analysis-tool#164]
Hi,
This check appears as failed although SSO is enabled on account level.
I guess it only checks for enablement in the Workspace level, but it is disabled when Unified Login is enabled.
This check should be updated to see if `Unified Login` is enabled, and if so, then this check should pass.

P.S
Same for `IA-2 - SCIM for user provisioning`

**Comment by arunpamulapati** [comment]
Hi. Thanks for the issue.  It is likely you missed the self attestation.  https://github.com/databricks-industry-solutions/security-analysis-tool/blob/main/docs/setup.md#usage
Specifically: Note: Go to Workspace -> Applications -> SAT -> files -> self_assessment_checks.yaml and make sure the "enabled" values reflect your environment for the listed manual checks with either true or false. SAT will automatically check the rest of the configurations.

We are adding this note to Dashboard as you are not alone to overlook this. There are 5 checks we don't have an API for that we need customers to attest on their own. This is to educate customers due to the importance of these items.
