### ISSUE TITLE
align documentation

### ISSUE THREAD

**Issue by NathNachtje** [databricks-industry-solutions/security-analysis-tool#37]
Can you align the bulletpoints under here: "You will need the following information to set up SAT, we will show you how to gather them in the next section" with what's  under the prerequisites. Needed some time with authentication, secrets and pat tokens

**Comment by arunpamulapati** [comment]
Hi Thank you for reaching out. Thanks for your feedback, we will take care of the alignment issue early next week.  I am happy to help with setting up the tool if you need some time. Please reach me at arun@databricks.com with a few days and times that work best for you so that we can coordinate calendars and get on a call if that is something you are looking for her.
Thank you.

**Comment by arunpamulapati** [comment]
Updated the instructions to align with the prereqs with numbers and order.
